/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sensing.core.thrift.cmp.bean;

@SuppressWarnings({"all"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-07-03")
public class Cmp1vnRetInfo implements org.apache.thrift.TBase<Cmp1vnRetInfo, Cmp1vnRetInfo._Fields>, java.io.Serializable, Cloneable, Comparable<Cmp1vnRetInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Cmp1vnRetInfo");

  private static final org.apache.thrift.protocol.TField ERR_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("errCode", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField DBID_FIELD_DESC = new org.apache.thrift.protocol.TField("DBID", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField SI_FIELD_DESC = new org.apache.thrift.protocol.TField("si", org.apache.thrift.protocol.TType.LIST, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new Cmp1vnRetInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new Cmp1vnRetInfoTupleSchemeFactory();

  public int errCode; // required
  public int DBID; // required
  public java.util.List<ScoreInfo> si; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ERR_CODE((short)1, "errCode"),
    DBID((short)2, "DBID"),
    SI((short)3, "si");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ERR_CODE
          return ERR_CODE;
        case 2: // DBID
          return DBID;
        case 3: // SI
          return SI;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ERRCODE_ISSET_ID = 0;
  private static final int __DBID_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ERR_CODE, new org.apache.thrift.meta_data.FieldMetaData("errCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.DBID, new org.apache.thrift.meta_data.FieldMetaData("DBID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SI, new org.apache.thrift.meta_data.FieldMetaData("si", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ScoreInfo.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Cmp1vnRetInfo.class, metaDataMap);
  }

  public Cmp1vnRetInfo() {
  }

  public Cmp1vnRetInfo(
    int errCode,
    int DBID,
    java.util.List<ScoreInfo> si)
  {
    this();
    this.errCode = errCode;
    setErrCodeIsSet(true);
    this.DBID = DBID;
    setDBIDIsSet(true);
    this.si = si;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Cmp1vnRetInfo(Cmp1vnRetInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.errCode = other.errCode;
    this.DBID = other.DBID;
    if (other.isSetSi()) {
      java.util.List<ScoreInfo> __this__si = new java.util.ArrayList<ScoreInfo>(other.si.size());
      for (ScoreInfo other_element : other.si) {
        __this__si.add(new ScoreInfo(other_element));
      }
      this.si = __this__si;
    }
  }

  public Cmp1vnRetInfo deepCopy() {
    return new Cmp1vnRetInfo(this);
  }

  @Override
  public void clear() {
    setErrCodeIsSet(false);
    this.errCode = 0;
    setDBIDIsSet(false);
    this.DBID = 0;
    this.si = null;
  }

  public int getErrCode() {
    return this.errCode;
  }

  public Cmp1vnRetInfo setErrCode(int errCode) {
    this.errCode = errCode;
    setErrCodeIsSet(true);
    return this;
  }

  public void unsetErrCode() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ERRCODE_ISSET_ID);
  }

  /** Returns true if field errCode is set (has been assigned a value) and false otherwise */
  public boolean isSetErrCode() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ERRCODE_ISSET_ID);
  }

  public void setErrCodeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ERRCODE_ISSET_ID, value);
  }

  public int getDBID() {
    return this.DBID;
  }

  public Cmp1vnRetInfo setDBID(int DBID) {
    this.DBID = DBID;
    setDBIDIsSet(true);
    return this;
  }

  public void unsetDBID() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DBID_ISSET_ID);
  }

  /** Returns true if field DBID is set (has been assigned a value) and false otherwise */
  public boolean isSetDBID() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DBID_ISSET_ID);
  }

  public void setDBIDIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DBID_ISSET_ID, value);
  }

  public int getSiSize() {
    return (this.si == null) ? 0 : this.si.size();
  }

  public java.util.Iterator<ScoreInfo> getSiIterator() {
    return (this.si == null) ? null : this.si.iterator();
  }

  public void addToSi(ScoreInfo elem) {
    if (this.si == null) {
      this.si = new java.util.ArrayList<ScoreInfo>();
    }
    this.si.add(elem);
  }

  public java.util.List<ScoreInfo> getSi() {
    return this.si;
  }

  public Cmp1vnRetInfo setSi(java.util.List<ScoreInfo> si) {
    this.si = si;
    return this;
  }

  public void unsetSi() {
    this.si = null;
  }

  /** Returns true if field si is set (has been assigned a value) and false otherwise */
  public boolean isSetSi() {
    return this.si != null;
  }

  public void setSiIsSet(boolean value) {
    if (!value) {
      this.si = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case ERR_CODE:
      if (value == null) {
        unsetErrCode();
      } else {
        setErrCode((java.lang.Integer)value);
      }
      break;

    case DBID:
      if (value == null) {
        unsetDBID();
      } else {
        setDBID((java.lang.Integer)value);
      }
      break;

    case SI:
      if (value == null) {
        unsetSi();
      } else {
        setSi((java.util.List<ScoreInfo>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ERR_CODE:
      return getErrCode();

    case DBID:
      return getDBID();

    case SI:
      return getSi();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ERR_CODE:
      return isSetErrCode();
    case DBID:
      return isSetDBID();
    case SI:
      return isSetSi();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Cmp1vnRetInfo)
      return this.equals((Cmp1vnRetInfo)that);
    return false;
  }

  public boolean equals(Cmp1vnRetInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_errCode = true;
    boolean that_present_errCode = true;
    if (this_present_errCode || that_present_errCode) {
      if (!(this_present_errCode && that_present_errCode))
        return false;
      if (this.errCode != that.errCode)
        return false;
    }

    boolean this_present_DBID = true;
    boolean that_present_DBID = true;
    if (this_present_DBID || that_present_DBID) {
      if (!(this_present_DBID && that_present_DBID))
        return false;
      if (this.DBID != that.DBID)
        return false;
    }

    boolean this_present_si = true && this.isSetSi();
    boolean that_present_si = true && that.isSetSi();
    if (this_present_si || that_present_si) {
      if (!(this_present_si && that_present_si))
        return false;
      if (!this.si.equals(that.si))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + errCode;

    hashCode = hashCode * 8191 + DBID;

    hashCode = hashCode * 8191 + ((isSetSi()) ? 131071 : 524287);
    if (isSetSi())
      hashCode = hashCode * 8191 + si.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Cmp1vnRetInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetErrCode()).compareTo(other.isSetErrCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetErrCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.errCode, other.errCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDBID()).compareTo(other.isSetDBID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDBID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.DBID, other.DBID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSi()).compareTo(other.isSetSi());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSi()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.si, other.si);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Cmp1vnRetInfo(");
    boolean first = true;

    sb.append("errCode:");
    sb.append(this.errCode);
    first = false;
    if (!first) sb.append(", ");
    sb.append("DBID:");
    sb.append(this.DBID);
    first = false;
    if (!first) sb.append(", ");
    sb.append("si:");
    if (this.si == null) {
      sb.append("null");
    } else {
      sb.append(this.si);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class Cmp1vnRetInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public Cmp1vnRetInfoStandardScheme getScheme() {
      return new Cmp1vnRetInfoStandardScheme();
    }
  }

  private static class Cmp1vnRetInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<Cmp1vnRetInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Cmp1vnRetInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ERR_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.errCode = iprot.readI32();
              struct.setErrCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DBID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.DBID = iprot.readI32();
              struct.setDBIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SI
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list16 = iprot.readListBegin();
                struct.si = new java.util.ArrayList<ScoreInfo>(_list16.size);
                ScoreInfo _elem17;
                for (int _i18 = 0; _i18 < _list16.size; ++_i18)
                {
                  _elem17 = new ScoreInfo();
                  _elem17.read(iprot);
                  struct.si.add(_elem17);
                }
                iprot.readListEnd();
              }
              struct.setSiIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Cmp1vnRetInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ERR_CODE_FIELD_DESC);
      oprot.writeI32(struct.errCode);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(DBID_FIELD_DESC);
      oprot.writeI32(struct.DBID);
      oprot.writeFieldEnd();
      if (struct.si != null) {
        oprot.writeFieldBegin(SI_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.si.size()));
          for (ScoreInfo _iter19 : struct.si)
          {
            _iter19.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class Cmp1vnRetInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public Cmp1vnRetInfoTupleScheme getScheme() {
      return new Cmp1vnRetInfoTupleScheme();
    }
  }

  private static class Cmp1vnRetInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<Cmp1vnRetInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Cmp1vnRetInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetErrCode()) {
        optionals.set(0);
      }
      if (struct.isSetDBID()) {
        optionals.set(1);
      }
      if (struct.isSetSi()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetErrCode()) {
        oprot.writeI32(struct.errCode);
      }
      if (struct.isSetDBID()) {
        oprot.writeI32(struct.DBID);
      }
      if (struct.isSetSi()) {
        {
          oprot.writeI32(struct.si.size());
          for (ScoreInfo _iter20 : struct.si)
          {
            _iter20.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Cmp1vnRetInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.errCode = iprot.readI32();
        struct.setErrCodeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.DBID = iprot.readI32();
        struct.setDBIDIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list21 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.si = new java.util.ArrayList<ScoreInfo>(_list21.size);
          ScoreInfo _elem22;
          for (int _i23 = 0; _i23 < _list21.size; ++_i23)
          {
            _elem22 = new ScoreInfo();
            _elem22.read(iprot);
            struct.si.add(_elem22);
          }
        }
        struct.setSiIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

