package com.sensing.core.thrift.cap.bean;
/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2019-01-02")
public class LbChannelInfo implements org.apache.thrift.TBase<LbChannelInfo, LbChannelInfo._Fields>, java.io.Serializable, Cloneable, Comparable<LbChannelInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("LbChannelInfo");

  private static final org.apache.thrift.protocol.TField LST_CHANNEL_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("lstChannelInfo", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new LbChannelInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new LbChannelInfoTupleSchemeFactory();

  public java.util.List<CapChannelWatch> lstChannelInfo; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LST_CHANNEL_INFO((short)1, "lstChannelInfo");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LST_CHANNEL_INFO
          return LST_CHANNEL_INFO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LST_CHANNEL_INFO, new org.apache.thrift.meta_data.FieldMetaData("lstChannelInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, CapChannelWatch.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(LbChannelInfo.class, metaDataMap);
  }

  public LbChannelInfo() {
  }

  public LbChannelInfo(
    java.util.List<CapChannelWatch> lstChannelInfo)
  {
    this();
    this.lstChannelInfo = lstChannelInfo;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public LbChannelInfo(LbChannelInfo other) {
    if (other.isSetLstChannelInfo()) {
      java.util.List<CapChannelWatch> __this__lstChannelInfo = new java.util.ArrayList<CapChannelWatch>(other.lstChannelInfo.size());
      for (CapChannelWatch other_element : other.lstChannelInfo) {
        __this__lstChannelInfo.add(new CapChannelWatch(other_element));
      }
      this.lstChannelInfo = __this__lstChannelInfo;
    }
  }

  public LbChannelInfo deepCopy() {
    return new LbChannelInfo(this);
  }

  @Override
  public void clear() {
    this.lstChannelInfo = null;
  }

  public int getLstChannelInfoSize() {
    return (this.lstChannelInfo == null) ? 0 : this.lstChannelInfo.size();
  }

  public java.util.Iterator<CapChannelWatch> getLstChannelInfoIterator() {
    return (this.lstChannelInfo == null) ? null : this.lstChannelInfo.iterator();
  }

  public void addToLstChannelInfo(CapChannelWatch elem) {
    if (this.lstChannelInfo == null) {
      this.lstChannelInfo = new java.util.ArrayList<CapChannelWatch>();
    }
    this.lstChannelInfo.add(elem);
  }

  public java.util.List<CapChannelWatch> getLstChannelInfo() {
    return this.lstChannelInfo;
  }

  public LbChannelInfo setLstChannelInfo(java.util.List<CapChannelWatch> lstChannelInfo) {
    this.lstChannelInfo = lstChannelInfo;
    return this;
  }

  public void unsetLstChannelInfo() {
    this.lstChannelInfo = null;
  }

  /** Returns true if field lstChannelInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetLstChannelInfo() {
    return this.lstChannelInfo != null;
  }

  public void setLstChannelInfoIsSet(boolean value) {
    if (!value) {
      this.lstChannelInfo = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case LST_CHANNEL_INFO:
      if (value == null) {
        unsetLstChannelInfo();
      } else {
        setLstChannelInfo((java.util.List<CapChannelWatch>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case LST_CHANNEL_INFO:
      return getLstChannelInfo();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case LST_CHANNEL_INFO:
      return isSetLstChannelInfo();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof LbChannelInfo)
      return this.equals((LbChannelInfo)that);
    return false;
  }

  public boolean equals(LbChannelInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_lstChannelInfo = true && this.isSetLstChannelInfo();
    boolean that_present_lstChannelInfo = true && that.isSetLstChannelInfo();
    if (this_present_lstChannelInfo || that_present_lstChannelInfo) {
      if (!(this_present_lstChannelInfo && that_present_lstChannelInfo))
        return false;
      if (!this.lstChannelInfo.equals(that.lstChannelInfo))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetLstChannelInfo()) ? 131071 : 524287);
    if (isSetLstChannelInfo())
      hashCode = hashCode * 8191 + lstChannelInfo.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(LbChannelInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetLstChannelInfo()).compareTo(other.isSetLstChannelInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLstChannelInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lstChannelInfo, other.lstChannelInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("LbChannelInfo(");
    boolean first = true;

    sb.append("lstChannelInfo:");
    if (this.lstChannelInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.lstChannelInfo);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LbChannelInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public LbChannelInfoStandardScheme getScheme() {
      return new LbChannelInfoStandardScheme();
    }
  }

  private static class LbChannelInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<LbChannelInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, LbChannelInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LST_CHANNEL_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list80 = iprot.readListBegin();
                struct.lstChannelInfo = new java.util.ArrayList<CapChannelWatch>(_list80.size);
                CapChannelWatch _elem81;
                for (int _i82 = 0; _i82 < _list80.size; ++_i82)
                {
                  _elem81 = new CapChannelWatch();
                  _elem81.read(iprot);
                  struct.lstChannelInfo.add(_elem81);
                }
                iprot.readListEnd();
              }
              struct.setLstChannelInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, LbChannelInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.lstChannelInfo != null) {
        oprot.writeFieldBegin(LST_CHANNEL_INFO_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.lstChannelInfo.size()));
          for (CapChannelWatch _iter83 : struct.lstChannelInfo)
          {
            _iter83.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LbChannelInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public LbChannelInfoTupleScheme getScheme() {
      return new LbChannelInfoTupleScheme();
    }
  }

  private static class LbChannelInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<LbChannelInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, LbChannelInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetLstChannelInfo()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetLstChannelInfo()) {
        {
          oprot.writeI32(struct.lstChannelInfo.size());
          for (CapChannelWatch _iter84 : struct.lstChannelInfo)
          {
            _iter84.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, LbChannelInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list85 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.lstChannelInfo = new java.util.ArrayList<CapChannelWatch>(_list85.size);
          CapChannelWatch _elem86;
          for (int _i87 = 0; _i87 < _list85.size; ++_i87)
          {
            _elem86 = new CapChannelWatch();
            _elem86.read(iprot);
            struct.lstChannelInfo.add(_elem86);
          }
        }
        struct.setLstChannelInfoIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

