package com.sensing.core.thrift.serverconfig;

/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-09-10")
public class InfoDetectFeatures implements org.apache.thrift.TBase<InfoDetectFeatures, InfoDetectFeatures._Fields>, java.io.Serializable, Cloneable, Comparable<InfoDetectFeatures> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("InfoDetectFeatures");

  private static final org.apache.thrift.protocol.TField I_RET_FIELD_DESC = new org.apache.thrift.protocol.TField("iRet", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField STR_RESULT_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("strResultInfo", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new InfoDetectFeaturesStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new InfoDetectFeaturesTupleSchemeFactory();

  public int iRet; // required
  public String strResultInfo; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    I_RET((short)1, "iRet"),
    STR_RESULT_INFO((short)2, "strResultInfo");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // I_RET
          return I_RET;
        case 2: // STR_RESULT_INFO
          return STR_RESULT_INFO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __IRET_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.I_RET, new org.apache.thrift.meta_data.FieldMetaData("iRet", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.STR_RESULT_INFO, new org.apache.thrift.meta_data.FieldMetaData("strResultInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(InfoDetectFeatures.class, metaDataMap);
  }

  public InfoDetectFeatures() {
  }

  public InfoDetectFeatures(
    int iRet,
    String strResultInfo)
  {
    this();
    this.iRet = iRet;
    setIRetIsSet(true);
    this.strResultInfo = strResultInfo;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public InfoDetectFeatures(InfoDetectFeatures other) {
    __isset_bitfield = other.__isset_bitfield;
    this.iRet = other.iRet;
    if (other.isSetStrResultInfo()) {
      this.strResultInfo = other.strResultInfo;
    }
  }

  public InfoDetectFeatures deepCopy() {
    return new InfoDetectFeatures(this);
  }

  @Override
  public void clear() {
    setIRetIsSet(false);
    this.iRet = 0;
    this.strResultInfo = null;
  }

  public int getIRet() {
    return this.iRet;
  }

  public InfoDetectFeatures setIRet(int iRet) {
    this.iRet = iRet;
    setIRetIsSet(true);
    return this;
  }

  public void unsetIRet() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __IRET_ISSET_ID);
  }

  /** Returns true if field iRet is set (has been assigned a value) and false otherwise */
  public boolean isSetIRet() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __IRET_ISSET_ID);
  }

  public void setIRetIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __IRET_ISSET_ID, value);
  }

  public String getStrResultInfo() {
    return this.strResultInfo;
  }

  public InfoDetectFeatures setStrResultInfo(String strResultInfo) {
    this.strResultInfo = strResultInfo;
    return this;
  }

  public void unsetStrResultInfo() {
    this.strResultInfo = null;
  }

  /** Returns true if field strResultInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetStrResultInfo() {
    return this.strResultInfo != null;
  }

  public void setStrResultInfoIsSet(boolean value) {
    if (!value) {
      this.strResultInfo = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case I_RET:
      if (value == null) {
        unsetIRet();
      } else {
        setIRet((Integer)value);
      }
      break;

    case STR_RESULT_INFO:
      if (value == null) {
        unsetStrResultInfo();
      } else {
        setStrResultInfo((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case I_RET:
      return getIRet();

    case STR_RESULT_INFO:
      return getStrResultInfo();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case I_RET:
      return isSetIRet();
    case STR_RESULT_INFO:
      return isSetStrResultInfo();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof InfoDetectFeatures)
      return this.equals((InfoDetectFeatures)that);
    return false;
  }

  public boolean equals(InfoDetectFeatures that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_iRet = true;
    boolean that_present_iRet = true;
    if (this_present_iRet || that_present_iRet) {
      if (!(this_present_iRet && that_present_iRet))
        return false;
      if (this.iRet != that.iRet)
        return false;
    }

    boolean this_present_strResultInfo = true && this.isSetStrResultInfo();
    boolean that_present_strResultInfo = true && that.isSetStrResultInfo();
    if (this_present_strResultInfo || that_present_strResultInfo) {
      if (!(this_present_strResultInfo && that_present_strResultInfo))
        return false;
      if (!this.strResultInfo.equals(that.strResultInfo))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + iRet;

    hashCode = hashCode * 8191 + ((isSetStrResultInfo()) ? 131071 : 524287);
    if (isSetStrResultInfo())
      hashCode = hashCode * 8191 + strResultInfo.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(InfoDetectFeatures other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetIRet()).compareTo(other.isSetIRet());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIRet()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.iRet, other.iRet);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStrResultInfo()).compareTo(other.isSetStrResultInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStrResultInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.strResultInfo, other.strResultInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("InfoDetectFeatures(");
    boolean first = true;

    sb.append("iRet:");
    sb.append(this.iRet);
    first = false;
    if (!first) sb.append(", ");
    sb.append("strResultInfo:");
    if (this.strResultInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.strResultInfo);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class InfoDetectFeaturesStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public InfoDetectFeaturesStandardScheme getScheme() {
      return new InfoDetectFeaturesStandardScheme();
    }
  }

  private static class InfoDetectFeaturesStandardScheme extends org.apache.thrift.scheme.StandardScheme<InfoDetectFeatures> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, InfoDetectFeatures struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // I_RET
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.iRet = iprot.readI32();
              struct.setIRetIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // STR_RESULT_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.strResultInfo = iprot.readString();
              struct.setStrResultInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, InfoDetectFeatures struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(I_RET_FIELD_DESC);
      oprot.writeI32(struct.iRet);
      oprot.writeFieldEnd();
      if (struct.strResultInfo != null) {
        oprot.writeFieldBegin(STR_RESULT_INFO_FIELD_DESC);
        oprot.writeString(struct.strResultInfo);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class InfoDetectFeaturesTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public InfoDetectFeaturesTupleScheme getScheme() {
      return new InfoDetectFeaturesTupleScheme();
    }
  }

  private static class InfoDetectFeaturesTupleScheme extends org.apache.thrift.scheme.TupleScheme<InfoDetectFeatures> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, InfoDetectFeatures struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetIRet()) {
        optionals.set(0);
      }
      if (struct.isSetStrResultInfo()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetIRet()) {
        oprot.writeI32(struct.iRet);
      }
      if (struct.isSetStrResultInfo()) {
        oprot.writeString(struct.strResultInfo);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, InfoDetectFeatures struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.iRet = iprot.readI32();
        struct.setIRetIsSet(true);
      }
      if (incoming.get(1)) {
        struct.strResultInfo = iprot.readString();
        struct.setStrResultInfoIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

