/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sensing.core.thrift.cmp.bean;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "all"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-07-03")
public class DBInfo implements org.apache.thrift.TBase<DBInfo, DBInfo._Fields>, java.io.Serializable, Cloneable, Comparable<DBInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DBInfo");

  private static final org.apache.thrift.protocol.TField DBID_FIELD_DESC = new org.apache.thrift.protocol.TField("DBID", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField CAPACITY_FIELD_DESC = new org.apache.thrift.protocol.TField("Capacity", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField SIZE_FIELD_DESC = new org.apache.thrift.protocol.TField("Size", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new DBInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new DBInfoTupleSchemeFactory();

  public int DBID; // required
  public int Capacity; // required
  public int Size; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DBID((short)1, "DBID"),
    CAPACITY((short)2, "Capacity"),
    SIZE((short)3, "Size");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DBID
          return DBID;
        case 2: // CAPACITY
          return CAPACITY;
        case 3: // SIZE
          return SIZE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __DBID_ISSET_ID = 0;
  private static final int __CAPACITY_ISSET_ID = 1;
  private static final int __SIZE_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DBID, new org.apache.thrift.meta_data.FieldMetaData("DBID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CAPACITY, new org.apache.thrift.meta_data.FieldMetaData("Capacity", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SIZE, new org.apache.thrift.meta_data.FieldMetaData("Size", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DBInfo.class, metaDataMap);
  }

  public DBInfo() {
  }

  public DBInfo(
    int DBID,
    int Capacity,
    int Size)
  {
    this();
    this.DBID = DBID;
    setDBIDIsSet(true);
    this.Capacity = Capacity;
    setCapacityIsSet(true);
    this.Size = Size;
    setSizeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DBInfo(DBInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.DBID = other.DBID;
    this.Capacity = other.Capacity;
    this.Size = other.Size;
  }

  public DBInfo deepCopy() {
    return new DBInfo(this);
  }

  @Override
  public void clear() {
    setDBIDIsSet(false);
    this.DBID = 0;
    setCapacityIsSet(false);
    this.Capacity = 0;
    setSizeIsSet(false);
    this.Size = 0;
  }

  public int getDBID() {
    return this.DBID;
  }

  public DBInfo setDBID(int DBID) {
    this.DBID = DBID;
    setDBIDIsSet(true);
    return this;
  }

  public void unsetDBID() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DBID_ISSET_ID);
  }

  /** Returns true if field DBID is set (has been assigned a value) and false otherwise */
  public boolean isSetDBID() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DBID_ISSET_ID);
  }

  public void setDBIDIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DBID_ISSET_ID, value);
  }

  public int getCapacity() {
    return this.Capacity;
  }

  public DBInfo setCapacity(int Capacity) {
    this.Capacity = Capacity;
    setCapacityIsSet(true);
    return this;
  }

  public void unsetCapacity() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CAPACITY_ISSET_ID);
  }

  /** Returns true if field Capacity is set (has been assigned a value) and false otherwise */
  public boolean isSetCapacity() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CAPACITY_ISSET_ID);
  }

  public void setCapacityIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CAPACITY_ISSET_ID, value);
  }

  public int getSize() {
    return this.Size;
  }

  public DBInfo setSize(int Size) {
    this.Size = Size;
    setSizeIsSet(true);
    return this;
  }

  public void unsetSize() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SIZE_ISSET_ID);
  }

  /** Returns true if field Size is set (has been assigned a value) and false otherwise */
  public boolean isSetSize() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SIZE_ISSET_ID);
  }

  public void setSizeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SIZE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case DBID:
      if (value == null) {
        unsetDBID();
      } else {
        setDBID((java.lang.Integer)value);
      }
      break;

    case CAPACITY:
      if (value == null) {
        unsetCapacity();
      } else {
        setCapacity((java.lang.Integer)value);
      }
      break;

    case SIZE:
      if (value == null) {
        unsetSize();
      } else {
        setSize((java.lang.Integer)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case DBID:
      return getDBID();

    case CAPACITY:
      return getCapacity();

    case SIZE:
      return getSize();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case DBID:
      return isSetDBID();
    case CAPACITY:
      return isSetCapacity();
    case SIZE:
      return isSetSize();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof DBInfo)
      return this.equals((DBInfo)that);
    return false;
  }

  public boolean equals(DBInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_DBID = true;
    boolean that_present_DBID = true;
    if (this_present_DBID || that_present_DBID) {
      if (!(this_present_DBID && that_present_DBID))
        return false;
      if (this.DBID != that.DBID)
        return false;
    }

    boolean this_present_Capacity = true;
    boolean that_present_Capacity = true;
    if (this_present_Capacity || that_present_Capacity) {
      if (!(this_present_Capacity && that_present_Capacity))
        return false;
      if (this.Capacity != that.Capacity)
        return false;
    }

    boolean this_present_Size = true;
    boolean that_present_Size = true;
    if (this_present_Size || that_present_Size) {
      if (!(this_present_Size && that_present_Size))
        return false;
      if (this.Size != that.Size)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + DBID;

    hashCode = hashCode * 8191 + Capacity;

    hashCode = hashCode * 8191 + Size;

    return hashCode;
  }

  @Override
  public int compareTo(DBInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetDBID()).compareTo(other.isSetDBID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDBID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.DBID, other.DBID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCapacity()).compareTo(other.isSetCapacity());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCapacity()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Capacity, other.Capacity);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSize()).compareTo(other.isSetSize());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSize()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Size, other.Size);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("DBInfo(");
    boolean first = true;

    sb.append("DBID:");
    sb.append(this.DBID);
    first = false;
    if (!first) sb.append(", ");
    sb.append("Capacity:");
    sb.append(this.Capacity);
    first = false;
    if (!first) sb.append(", ");
    sb.append("Size:");
    sb.append(this.Size);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DBInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public DBInfoStandardScheme getScheme() {
      return new DBInfoStandardScheme();
    }
  }

  private static class DBInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<DBInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DBInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DBID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.DBID = iprot.readI32();
              struct.setDBIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CAPACITY
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.Capacity = iprot.readI32();
              struct.setCapacityIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SIZE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.Size = iprot.readI32();
              struct.setSizeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DBInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(DBID_FIELD_DESC);
      oprot.writeI32(struct.DBID);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(CAPACITY_FIELD_DESC);
      oprot.writeI32(struct.Capacity);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SIZE_FIELD_DESC);
      oprot.writeI32(struct.Size);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DBInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public DBInfoTupleScheme getScheme() {
      return new DBInfoTupleScheme();
    }
  }

  private static class DBInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<DBInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DBInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetDBID()) {
        optionals.set(0);
      }
      if (struct.isSetCapacity()) {
        optionals.set(1);
      }
      if (struct.isSetSize()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetDBID()) {
        oprot.writeI32(struct.DBID);
      }
      if (struct.isSetCapacity()) {
        oprot.writeI32(struct.Capacity);
      }
      if (struct.isSetSize()) {
        oprot.writeI32(struct.Size);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DBInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.DBID = iprot.readI32();
        struct.setDBIDIsSet(true);
      }
      if (incoming.get(1)) {
        struct.Capacity = iprot.readI32();
        struct.setCapacityIsSet(true);
      }
      if (incoming.get(2)) {
        struct.Size = iprot.readI32();
        struct.setSizeIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

